### ISSUE TITLE
M669 K1 with Firmware 2.03 and newer

### ISSUE THREAD

**Issue by xenon2008** [Duet3D/ConfigTool#26]
Hello together!

I am new und this is my first time with Reprap Firmware.
Currently i am building my first own Hypercube Evolution with a Duet 2 Wifi Board.
I have read in the Duet3d Documentation that with Firmware 2.03 and newer i have to set M669 K1 in config,g instead M669 S1 for my Hypercube Evolution CoreXY Printer.

Because i am new i want to use the RepRap Configuration Tool to build my first Base Config.
But now i have seen that in the config.g file from the configurator stands M669 S1 and not K1.
But i have choosen Firmware 2.03 and new in the Step before.

Is this a Bug or a mistake from me because i am new ?

Here is a link to the Site from Duet3D
[https://duet3d.dozuki.com/Wiki/ConfiguringRepRapFirmwareCoreXYPrinter](https://duet3d.dozuki.com/Wiki/ConfiguringRepRapFirmwareCoreXYPrinter)

**Comment by chrishamm** [comment]
Thanks for the note, I'll fix that shortly in v3.1.0.
