### ISSUE TITLE
[Feature request] Add generic CoreXY as a preset

### ISSUE THREAD

**Issue by ThatJohn** [Duet3D/ConfigTool#28]
Finishing a Hypercube Evolution build, would be useful to have a generic Hypercube preset to use as a base.

**Comment by chrishamm** [comment]
Please feel free to share your JSON template for the Hypercube. Since I don't have one, I cannot test it, but I would be happy to add it as a preset.

**Comment by chrishamm** [comment]
I am closing this due to lack of feedback.
