### ISSUE TITLE
RRF3 Config without heated bed results in no heaters

### ISSUE THREAD

**Issue by NextDesign1** [Duet3D/ConfigTool#29]
Hi there,

If you try to configure a printer without a heated bed with RRF v3, when you click the "remove heater" button under "I/O Mapping" to remove one of the heaters, if you then try to change the type to "Nozzle", all heaters will be removed. If you try to add another one back in, if you go to the "Fans" page,  you are unable to set thermostatic control to E0 - it will still say "Bed". If you go to "Tools", it will have "n/a" under "Heaters".

**Comment by chrishamm** [comment]
Thanks, I'll fix this shortly in v3.1.0.
