### ISSUE TITLE
[Feature requests] Upgrading firmware from 2.X to 3.X options

### ISSUE THREAD

**Issue by BL8900** [Duet3D/ConfigTool#36]
1) The tool didn't have an option to enable PanelDue as noted in Duet3D's [documentation](https://duet3d.dozuki.com/Wiki/Connecting_an_LCD_control_panel#Section_PanelDue_config_g_setup_for_RepRapFirmware_Num_3) with RRF3 selected in general settings and 
in config.g
` M575 P1 S1 B57600` 
is needed to enable a PanelDue. Perhaps a checkbox in the general settings would be quite helpful.

2) Normally Open switch end stops option is no longer present. Per Duet3D's [documentation](https://duet3d.dozuki.com/Wiki/RepRapFirmware_3_overview#Section_M574) the config just needs a '!' before the pin name. For e.g., change
`M574 X1 S1 P"xstop"`
to
`M574 X1 S1 P"!xstop"`

Would be nice to see the Normally Open switch buttons from 2.x config. Thanks for looking.

**Comment by chrishamm** [comment]
Thanks for the note, I've added support for 1. You can already change the pin level on the I/O Mapping page for switches but to make things clearer, I've changed the 'inverted' text to 'active-low'.
