### ISSUE TITLE
Configuration tool missing some items

### ISSUE THREAD

**Issue by Lukaslozo** [Duet3D/ConfigTool#39]
Its a very handy tool, but a few important points.

Whats missing is being able to add multiple X,Y or Z motors and map them to a axis.

Adding a motor always seems to add it as a extruder motor not a axis motor.

This always becomes confusing when using a expansion board.

thanks

**Comment by chrishamm** [comment]
This is a duplicate of #21. It is planned and will be added once the config tool uses the same object model as RepRapFirmware/DSF.
