### ISSUE TITLE
Change wording for M501 option?

### ISSUE THREAD

**Issue by beikeland** [Duet3D/ConfigTool#43]
https://github.com/Duet3D/ConfigTool/blob/e8e4294a543c34d52ef26fcb3abada2be50adfb6/src/views/General.vue#L40

Could this include a note to indicate its an EEPROM replacement for the uninitiated user coming from marlin/repeteir?

As well as a general discussion on weather or not it could be default to on? I'd think a user who knows he doesn't need it is more likely to uncheck the box than a user who doesn't know he needs it is likely to check the box?

Triggered by https://forum.duet3d.com/topic/17680/rrf-makes-me-feel-stupid-rant-just-ignore-me

**Comment by chrishamm** [comment]
Thanks for pointing this out, we'll change the description in the next version.
