### ISSUE TITLE
Change wording for leadscrew options to account for multi-start screws

### ISSUE THREAD

**Issue by beikeland** [Duet3D/ConfigTool#44]
Unclear when using multistart leadscrew like the recently popular TR8x2 where the pitch is not the same as the lead

Ref https://forum.duet3d.com/topic/17856/rrf-configurator-is-it-pitch-or-lead

Either clarify to use lead for multi start screws or add options that takes both pitch and lead?

**Comment by chrishamm** [comment]
Thanks for the note, I'll change it shortly.
