### ISSUE TITLE
Duet 2 BLTouch No addon PWM can't select heater 3

### ISSUE THREAD

**Issue by StephenRC** [Duet3D/ConfigTool#48]
No addon boards.
Board: Duet 2 Ethernet (2Ethernet)
Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 3.1.1 (2020-05-19b2)

Only the duex pwm pins can be selected.

**Comment by StephenRC** [comment]
Further checking it's only for the Duet 2 Ethernet.  The wifi selection shows the heaters for pwm.

**Comment by chrishamm** [comment]
Thanks, I'll fix it soon.
