### ISSUE TITLE
Comment regarding placement of zprobe

### ISSUE THREAD

**Issue by jaysuk** [Duet3D/ConfigTool#51]
On the endstop configuration page, the comment 
`This switch must be connected to the Z probe terminal and not to the Z endstop switch terminal!`
Is shown when selecting an endstop.
For the Duet 2/maestro, this comment is not applicable to RRF3 as the zstop could also be used.
This comment is also displayed for the duet 3 which does not have a dedicated zprobe header.

**Comment by jaysuk** [comment]
I have created a pull request https://github.com/Duet3D/ConfigTool/pull/52

**Comment by chrishamm** [comment]
Thanks, merged as well.
