### ISSUE TITLE
Duet 3 Extension Board 3HC OUT Pins incorrect

### ISSUE THREAD

**Issue by slideup-benni** [Duet3D/ConfigTool#54]
Hello,

it looks like the definition of the fan out pins is incorrect, it should be out3 to out8.

https://github.com/Duet3D/ConfigTool/blob/e5161883f73d8702cf22ff5ab4f23fd084a61e66/src/store/ExpansionBoards.js#L37

Please take a look at [https://duet3d.dozuki.com/Wiki/Duet_3_Expansion_3HC_Wiring_Diagram](https://duet3d.dozuki.com/Wiki/Duet_3_Expansion_3HC_Wiring_Diagram)

Can you change this, please.
Thanks, Benjamin

**Comment by slideup-benni** [comment]
I found more:
- out3 is missing for Duet 3 Mainboard
- all ioX are missing for z-probe "input pin" for ext3hc
- io2.out, io3.out, io5.out and io0.out are missing for z-probe "pwm control channel" for ext3hc

**Comment by StephenRC** [comment]
Also, for the 1LC, you can't select io_0.in for the pwm.

**Comment by chrishamm** [comment]
Thanks, I'll add new pin definitions soon.

@slideup-benni io0.out, io2.out, io3.out, and io5.out do not support PWM. See https://duet3d.dozuki.com/Wiki/Duet_3_Expansion_Hardware_Overview#Section_IO
