### ISSUE TITLE
overwiriting files with blank data is not useful

### ISSUE THREAD

**Issue by xvart** [Duet3D/ConfigTool#57]
I make changes to stop.g and the tool decides it's going to build a new empty file and there appears to be no way to have stop.g omitted from the zip dump I import into a duet board.

There needs to be an initial reference mode and an update mode where empty files are not built in update mode.

**Comment by chrishamm** [comment]
At present the config tool is intended to give you a first starting point that you can enhance further on demand. It isn't intended to read back and forth your config files so I cannot help you there.

The next version will allow you to configure the machine as you wish (of course still excluding macro files like stop.g or pause.g) and then pass the machine config to the config tool, which will then turn it into a config.g file.
