### ISSUE TITLE
ConfigTool

### ISSUE THREAD

**Issue by Makeamaker** [Duet3D/ConfigTool#62]
it is impossible for the web to generate a ZIP file.

it keeps generating the file but does not give the option to download it

**Comment by Makeamaker** [comment]
![Sin título](https://user-images.githubusercontent.com/77164057/104040039-72c0f980-51d7-11eb-882d-a18cf3c1739c.png)

**Comment by chrishamm** [comment]
Thanks, I've got a fix ready but it will take approx one more hour before I can apply it. The assets on the configtool server were broken but I've deleted them temporarily so the error message should be gone when you clear your cache. Alternatively disable the "Get DWC" and "Get RRF" checkboxes and then generate the ZIP file.
