### ISSUE TITLE
Static IP Settings does not work due to wrong gcode command

### ISSUE THREAD

**Issue by bigjim80** [Duet3D/ConfigTool#63]
For Duet2 WiFi: When Choosing Static IP / Subnet / Gateway in the Network Tab, this is translated in runonce.g into

M587 S"ssid" P"password" I(ip address) J(netmask) K(gateway)

But this should be

M587 S"ssid" P"password" I(ip address) J(gateway) K(netmask)

**Comment by chrishamm** [comment]
Thanks for reporting this, it's been fixed in v3.2.3.
