### ISSUE TITLE
Definition of delta printer on duet 3 MB6XD board

### ISSUE THREAD

**Issue by Holst1901** [Duet3D/ConfigTool#80]
I think I found a problem
The delta definition is not correct
The rod length value is not written to the config.g file.

; Kinematics
M665 R240 B175 H378

If I add the value manually

; Kinematics
M665 R240 B175 L446 H378

Every thing is working fine.

A second point is the homedelta.g file

There this " is wrong.

When I delete this character everything works

G1 H2 X-10 Y-10 Z-10 F12000

**Comment by chrishamm** [comment]
Thanks, I can confirm these issues. They will be fixed in 3.5.0-rc.4.
