### ISSUE TITLE
generated homex.g file might cause print head to crash into bed

### ISSUE THREAD

**Issue by NNygren** [Duet3D/ConfigTool#81]
`; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.3+2 on Fri Apr 05 2024 23:17:10 GMT-0500 (Central Daylight Time)
 
; lift Z
G91 ; relative positioning
G1 H2 Z2 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning
 
; home X
var maxTravel = move.axes[0].max - move.axes[0].min + 5 ; calculate how far X can travel plus 5mm
G1 H1 X{-var.maxTravel} F6000 ; coarse home in the -X direction
G1 H2 X5 F6000 ; move back 5mm
G1 H1 X{-var.maxTravel} F3000 ; fine home in the -X direction
G1 H2 Z-2 F6000 ; lower Z again`

The generated homex.g file should probably have the G90 moved to the end of the file.  The final G1 to lower Z caused my print head to crash into the bed after a 'G28 X' was executed in my end gcode.

**Comment by chrishamm** [comment]
Sorry for this, it's now fixed in v3.5.0-rc.4+1.
